/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001d35",
        "surface-container-high": "#202c32",
        "on-tertiary-container": "#003458",
        "on-primary": "#562000",
        "on-secondary-fixed-variant": "#6c3a00",
        "tertiary": "#9ccaff",
        "surface-container-lowest": "#041015",
        "primary": "#ffb692",
        "surface-container-highest": "#2a363d",
        "inverse-surface": "#d7e4ec",
        "on-primary-fixed-variant": "#7a3000",
        "primary-container": "#ff6d00",
        "secondary-container": "#fd9000",
        "primary-fixed-dim": "#ffb692",
        "surface-bright": "#2f3b41",
        "outline": "#a98a7c",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface-variant": "#2a363d",
        "on-tertiary": "#003256",
        "on-surface-variant": "#e2bfb0",
        "outline-variant": "#594136",
        "tertiary-fixed": "#d0e4ff",
        "surface-dim": "#09151a",
        "on-primary-container": "#582100",
        "surface": "#09151a",
        "surface-container": "#152127",
        "tertiary-fixed-dim": "#9ccaff",
        "on-primary-fixed": "#341100",
        "on-secondary-container": "#613400",
        "on-tertiary-fixed-variant": "#00497a",
        "on-background": "#d7e4ec",
        "on-surface": "#d7e4ec",
        "secondary-fixed": "#ffdcc1",
        "on-secondary": "#4c2700",
        "error": "#ffb4ab",
        "inverse-primary": "#9f4200",
        "background": "#09151a",
        "on-secondary-fixed": "#2e1500",
        "inverse-on-surface": "#263238",
        "surface-tint": "#ffb692",
        "surface-container-low": "#111d23",
        "primary-fixed": "#ffdbcb",
        "tertiary-container": "#2a9ff9",
        "secondary": "#ffb778",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb778"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
